name: CI/CD Pipeline

# THE TRIGGER: When does this run?
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Permission to allow the robot to write to the website hosting
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# THE JOBS: What actually happens?
jobs:
  # CI Integration (Testing)
  build-and-test:
    # The computer OS we want to use (like renting a laptop for 1 min)
    runs-on: ubuntu-latest

    # The steps the robot takes
    steps:
      - name: Check out my code
        uses: actions/checkout@v3

      # NEW STEP: Set up Node.js (to run testing tool)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # NEW STEP: Install the testing tool (HTMLHint)
      - name: Install HTML Linter
        run: npm install -g htmlhint

      # NEW STEP: Run the test
      # This command checks all html files. If it finds errors, the pipeline STOPS.
      - name: Run HTML Test
        run: htmlhint *.html

      # NEW: Upload the files so Job 2 can see them
      # In GitHub Actions, jobs run on different computers. 
      # Job 1 computer deletes data when done. We must "Upload" the good code to a shared storage (Artifacts)      


      # CD Deploying(If tested then Deploy) 
  deploy-to-live:

    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

          # 1. Log in to Docker Hub using the Secrets we created
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
    
            # 2. Set up Docker Buildx (a tool to build images efficiently)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build and Push
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # NAMING CONVENTION: username/repository:tag
          # We use 'latest' as the tag for now.
          tags: ${{ secrets.DOCKER_USERNAME }}/cicd-learning:latest
