name: CI/CD Pipeline

# THE TRIGGER: When does this run?
on:
  push:
    branches: [ "master" ]

# Permission to allow the robot to write to the website hosting
permissions:
  contents: read
  pages: write
  id-token: write

# THE JOBS: What actually happens?
jobs:
  build-and-test:
    # The computer OS we want to use (like renting a laptop for 1 min)
    runs-on: ubuntu-latest

    # The steps the robot takes
    steps:
      - name: Check out my code
        uses: actions/checkout@v3

      # NEW STEP: Set up Node.js (to run testing tool)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # NEW STEP: Install the testing tool (HTMLHint)
      - name: Install HTML Linter
        run: npm install -g htmlhint

      # NEW STEP: Run the test
      # This command checks all html files. If it finds errors, the pipeline STOPS.
      - name: Run HTML Test
        run: htmlhint *.html

      # NEW: Upload the files so Job 2 can see them
      # In GitHub Actions, jobs run on different computers. 
      # Job 1 computer deletes data when done. We must "Upload" the good code to a shared storage (Artifacts)      
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  # JOB 2: DEPLOYMENT (Release)
  deploy-to-live:
    # IMPORTANT: "needs" means this job waits for 'build-and-test' to finish successfully.
    needs: build-and-test
    
    # This creates a specific environment url in GitHub UI
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
